services:
  - type: web
    name: gerador-de-contratos
    runtime: python
    buildCommand: apt-get update && apt-get install -y libreoffice --no-install-recommends && pip install -r requirements.txt
    startCommand: gunicorn app:app
